apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pn7b36hzr-python
  janus-idp.io/tekton: pn7b36hzr-python
  backstage.io/kubernetes-id: pn7b36hzr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pn7b36hzr-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
