apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pn7b36hzr-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:333ad46a5fc589cb582dbde9fa1c955695bf8f83@sha256:8dfec760d777ab5f49f92bfa4640e863f25f35e434d0dd53f5f1cfc43e60ceba
          name: container-image
